include ../shared.mk

CPP_SOURCES:=$(wildcard *.cpp)
CPP_SOURCES+=$(wildcard threads/*.cpp) # Include all C++ files in the Threads folder

C_SOURCES+=$(wildcard threads/*.c) # Include all C files in the Threads folder
C_SOURCES+=$(wildcard threads/sensors/*.c) # Include all C files in the Threads folder
# CFLAGS+=-Werror


include ../end.mk

